### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by 7flash** [junobuild/juno-js#80]
When trying to install recent package version in my react app, it throws an error, but older versions work

https://github.com/peterpeterparker/icdraw/issues/2

**Comment by peterpeterparker** [comment]
Fck me! I think I know what it is, it's because of changes in the packaging library of yesterday (using agent-js as peer dependencies) to solve an issue with Next.js. Let me try to fix that...

Thanks for the report.
